FROM rstahwalian/as-perl:apache2modperl

# Copy Apache configuration
COPY apache2/conf /usr/local/apache2/conf/

WORKDIR /dwc

# Expose HTTP port
EXPOSE 80

CMD ["/usr/local/apache2/bin/httpd", "-D", "FOREGROUND"]